//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazEmplames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA_IDENTIFICACION
    {
        public int bitacora_ident { get; set; }
        public Nullable<int> tarjeta { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<int> funcionario { get; set; }
        public short usuario { get; set; }
        public int tipo_log { get; set; }
        public string detalle { get; set; }
    
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
