//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazEmplames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public int funcionario1 { get; set; }
        public Nullable<int> unidad_organizacional { get; set; }
        public string nombre_funcionario { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string numero_funcionario { get; set; }
        public string telefono_funcionario { get; set; }
        public string fax_funcionario { get; set; }
        public string calle_funcionario { get; set; }
        public string colonia_funcionario { get; set; }
        public Nullable<short> ubicacion { get; set; }
        public string cp_funcionario { get; set; }
        public Nullable<short> estrategico { get; set; }
        public Nullable<byte> activo { get; set; }
        public string numero_registro { get; set; }
        public bool on_mni { get; set; }
        public bool on_bsi { get; set; }
        public bool on_harris { get; set; }
        public Nullable<int> cr_opera { get; set; }
        public bool bbvab { get; set; }
        public string unidad_organizacional_anterior { get; set; }
        public Nullable<int> cr_opera_term { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<System.DateTime> fecha_ult_modif { get; set; }
    }
}
