//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazEmplames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL_HEXA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERFIL_HEXA()
        {
            this.PERMISOS_X_USUARIO_HEXA = new HashSet<PERMISOS_X_USUARIO_HEXA>();
        }
    
        public short perfil { get; set; }
        public short aplicacion { get; set; }
        public string nombre_perfil { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public string masc_permisos { get; set; }
        public string masc_autorizaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISOS_X_USUARIO_HEXA> PERMISOS_X_USUARIO_HEXA { get; set; }
    }
}
