//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazEmplames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISOS_X_USUARIO_HEXA
    {
        public short perfil { get; set; }
        public short usuario { get; set; }
        public string masc_permisos { get; set; }
        public string masc_autorizaciones { get; set; }
    
        public virtual PERFIL_HEXA PERFIL_HEXA { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
