//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazEmplames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDAD_ORGANIZACIONAL_RESUMEN
    {
        public int funcionario { get; set; }
        public Nullable<int> unidad_organizacional_padre { get; set; }
        public string banca { get; set; }
        public string division { get; set; }
        public string cr { get; set; }
        public string plaza { get; set; }
        public string sucursal { get; set; }
        public string unidad_org_banca { get; set; }
        public string unidad_org_division { get; set; }
        public string unidad_org_creg { get; set; }
        public string unidad_org_plaza { get; set; }
        public string unidad_org_sucursal { get; set; }
    }
}
