//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazEmplames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.BITACORA_IDENTIFICACION = new HashSet<BITACORA_IDENTIFICACION>();
            this.PERMISOS_X_USUARIO_HEXA = new HashSet<PERMISOS_X_USUARIO_HEXA>();
        }
    
        public short usuario1 { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string kapiti { get; set; }
        public string nombre_usuario { get; set; }
        public Nullable<byte> origen_usuario { get; set; }
        public Nullable<System.DateTime> fecha_cambio_password { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_acceso { get; set; }
        public Nullable<byte> area_usuario { get; set; }
        public Nullable<byte> login_erroneo { get; set; }
        public string colores1 { get; set; }
        public string colores2 { get; set; }
        public string colores3 { get; set; }
        public string adm_dd { get; set; }
        public string ultimo_pwd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BITACORA_IDENTIFICACION> BITACORA_IDENTIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISOS_X_USUARIO_HEXA> PERMISOS_X_USUARIO_HEXA { get; set; }
    }
}
